[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*

addopts =
    --browser chromium
    --html=report.html
    --self-contained-html
    --output=test-results
    --screenshot=only-on-failure
    --full-page-screenshot
    --tracing=retain-on-failure
    --video=retain-on-failure

markers =
    e2e: complete end-to-end purchase journey
    negative: negative test scenario
    search: product search test scenario